name: Update version

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 1,5,13,17 * * *'

jobs:
  updateVersion:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: get latest ver from zen git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/updateVersion.sh
