name: Update version

on:
  workflow_dispatch: 
  schedule:
    - cron: '0,6,12,18 * * *'

jobs:
  updateVersion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Install Nix
        if: steps.check.outputs.should_update == 'true'
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: get latest ver from zen git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/updateVersion.sh
      - name: push diff
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/pushDiff.sh
